### ISSUE TITLE
Pull taxonomy from yaml file

### ISSUE THREAD

**Issue by hmsklee** [CreativeCodingLab/TextAnnotationGraphs#12]
https://github.com/clulab/reach/blob/master/main/src/main/resources/org/clulab/reach/biogrammar/taxonomy.yml

**Comment by myedibleenso** [comment]
@hmsklee, has this already been solved?  The demo loads the `taxonomy.yml` in the repo.

**Comment by hmsklee** [comment]
[ ] - add functionality to load other yml files
